packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - git
    - go
    - composer
    - wp-cli
    - telnet
  darwin:
    - subversion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  windows:
    - sudo
    - sliksvn
    - php
  servers:
    - crates.io/bat
    - crates.io/eza
    - starship.rs
    - crates.io/zoxide
