packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - fzf
    - fd
    - yazi
    - lazygit
  local:
    - git
    - go
    - composer
    - wp-cli
    - telnet
    - wezterm
    - ripgrep
    - bottom
  darwin:
    - subversion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-history-substring-search
    - font-jetbrains-mono-nerd-font
    - sevenzip
    - git-delta
  windows:
    - sudo
    - sliksvn
    - php
    - jetbrainsmono-nf
    - 7zip
    - delta
  servers:
    - rg
    - btm
    - delta
