packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - fzf
    - fd
    - lazygit
    - yazi
    - rclone
  local:
    - git
    - go
    - composer
    - wp-cli
    - telnet
    - wezterm
    - ripgrep
    - bottom
    - act
    - cloudflared
  darwin:
    - subversion
    - font-jetbrains-mono-nerd-font
    - git-delta
  windows:
    - sudo
    - sliksvn
    - php
    - jetbrainsmono-nf
    - delta
  servers:
    - rg
    - btm
    - delta
