packages:
  common:
    - git
    - bat
    - eza
    - delta
    - starship
    - zoxide
    - fzf
    - fd
    - lazygit
    - yazi
    - rclone
  local:
    - go
    - php
    - composer
    - wp-cli
    - telnet
    - wezterm
    - ripgrep
    - bottom
    - act
    - cloudflared
  darwin:
    - subversion
    - font-jetbrains-mono-nerd-font
  windows:
    - sudo
    - sliksvn
    - jetbrainsmono-nf
  servers:
    - rg
    - btm
