packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - fzf
    - fd
    - ripgrep
    - git
    - go
    - composer
    - wp-cli
    - telnet
  darwin:
    - subversion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-history-substring-search
  windows:
    - sudo
    - sliksvn
    - php
  servers:
    - crates.io/bat
    - crates.io/eza
    - starship.rs
    - crates.io/zoxide
    - github.com/junegunn/fzf
    - crates.io/fd-find
    - crates.io/ripgrep
