packages:
  common:
    - git
    - bat
    - eza
    - delta
    - starship
    - zoxide
    - fzf
    - fd
    - lazygit
    - yazi
    - jq
    - ffmpeg
    - imagemagick
    - rclone
  local:
    - go
    - php
    - composer
    - wp-cli
    - telnet
    - wezterm
    - ripgrep
    - bottom
    - act
    - cloudflared
    - poppler
    - resvg
  darwin:
    - sevenzip
    - subversion
    - font-jetbrains-mono-nerd-font
  windows:
    - 7zip
    - sudo
    - sliksvn
    - jetbrainsmono-nf
  servers:
    - rg
    - btm
