packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - fzf
    - fd
    - ripgrep
  local:
    - git
    - go
    - composer
    - wp-cli
    - telnet
  darwin:
    - subversion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-history-substring-search
  windows:
    - sudo
    - sliksvn
    - php
  servers:
