packages:
  common:
    - bat
    - eza
    - starship
    - zoxide
    - fzf
    - fd
    - rg
  local:
    - git
    - go
    - composer
    - wp-cli
    - telnet
    - wezterm
  darwin:
    - subversion
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-history-substring-search
    - font-jetbrains-mono-nerd-font
  windows:
    - sudo
    - sliksvn
    - php
    - jetbrainsmono-nf
  servers:
