gui:
  nerdFontsVersion: 3
  commitAuthorShortLength: 4
  commitAuthorLongLength: 12
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: 'arrowAndNumber'

git:
  paging:
    colorArg: always
    pager: delta --paging=never
